### PR TITLE
[FIX - DB] Models and migrations fix

### PR DESCRIPTION
**Pull request by marattagian**
## Fixing poject setup
Fix of some issues we ran into whit the setup of sequelize, particularly models and migrations.
### Evidence
Screenshot from 2022-07-18 20-57-13

image

image

### CODE REVIEW

**Review by R-Berrocal — APPROVED** [review]
Muy buen PR, todo ok.

**Review by gabodmc — APPROVED** [review]
Excelente fix gente!

**Review by HinojosaAcevedoJ — APPROVED** [review]
buen fix!

**Review by itsnicolearias — APPROVED** [review]
para mi esta bien :+1:

**Pull request merged**
