### PR TITLE
[COMMENTS] create model and migration - OT245-79

### PR DESCRIPTION
**Pull request by MauriDiPietro**
[OT245-79](https://alkemy-labs.atlassian.net/browse/OT245-79)

**_Description_**

AS user
I WANT to add a new comment to a post
TO comment on this post.

Criteria of acceptance:
The ability to add Comments to a Post will be added. The fields of a comment will be user_id, body and new_id

**_Evidence:_**

**Table comments relationship with user**

image

image

**case comment save relation with userId and newId existant in database ok:**

image

### CODE REVIEW

**Review by itsnicolearias — COMMENTED** [review]
Lo de postid es un error no? se habran confundido de modelo

**Comment by MauriDiPietro** [comment]
Nose, le iba a preguntar a Gabi en la daily, lo dejé comentado en la migración porque obviamente no está el modelo de Post

**Comment by itsnicolearias** [comment]
En la card 81 para crear comentarios, dice newsId

**Comment by MauriDiPietro** [comment]
> En la card 81 para crear comentarios, dice newsId

Entonces capaz que sea newId en vez de postId

**Review by itsnicolearias — APPROVED** [review]

**Review by DamiBastos — APPROVED** [review]

**Review by itsnicolearias — APPROVED** [review]

**Review by marattagian — APPROVED** [review]

**Review by CamiloLonM — APPROVED** [review]

**Pull request merged**
